# Generated by Django 3.2.3 on 2021-06-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_auto_20210604_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
